export const customConfig = {
   primary: '#fc055b',
   secondary: '#219aaf',
   accent: '#e8d03a',
   neutral: '#2A2730',
   'base-100': '#E3E3ED',
   '--rounded-box': '3rem',
   '--rounded-btn': '3rem',
};

export const myTheme = {
   "mytheme": {
      "primary": "#5d99e2",
      "secondary": "#b5e878",
      "accent": "#37fce8",
      "neutral": "#1a1a1a",
      "base-100": "#363c45",
      "info": "#70c4e1",
      "success": "#61e0cf",
      "warning": "#e89726",
      "error": "#ea2e57",
      "--rounded-box": "1rem",
      "--rounded-btn": "0.5rem",
      "--rounded-badge": "1.9rem",
      "--animation-btn": "0.25s",
      "--animation-input": "0.2s",
      "--btn-text-case": "uppercase",
      "--btn-focus-scale": "0.95",
      "--border-btn": "1px",
      "--tab-border": "1px",
      "--tab-radius": "0.5rem",
   }
};

export const Themes = [
   'light',
   'dark',
   'cupcake',
   'bumblebee',
   'emerald',
   'corporate',
   'synthwave',
   'retro',
   'cyberpunk',
   'valentine',
   'halloween',
   'garden',
   'forest',
   'aqua',
   'lofi',
   'pastel',
   'fantasy',
   'wireframe',
   'black',
   'luxury',
   'dracula',
   'cmyk',
   'autumn',
   'business',
   'acid',
   'lemonade',
   'night',
   'coffee',
   'winter',
   'procyon',
];